### ISSUE TITLE
Build problems after updating ember-l10n from 4.x to 5.x

### ISSUE THREAD

**Issue by progmatic-99** [Cropster/ember-l10n#99]
I upgraded ember-l10n(devDependency) package from 4.x to latest version which is 5.1.0, after that **ember serve** doesn't work.
I tried **uninstalling and reinstalling** the package, but no luck.

I get the error:
```
Build Error (CreateEmberL10nFastBootAssetMap)

ENOENT: no such file or directory, scandir '/tmp/broccoli-7518h8A17KW9hHxR/out-1002-append_ember_auto_import_analyzer//tmp/broccoli-7518h8A17KW9hHxR/out-1002-append_ember_auto_import_analyzer'
```

Here's the stack trace: https://pastebin.com/qCuWzCig

Output from ember version --verbose && npm --version && yarn --version:

```
ember version: octane
yarn version: 1.22.11
npm version: 6.14.15
```

**Comment by progmatic-99** [comment]
@mydea Can you take a look, please??

**Comment by mydea** [comment]
Hopefully this is fixed by updating dependencies. I'll cut a 5.2 release, let me know if there are still problems.

**Comment by progmatic-99** [comment]
@mydea Still getting the same error.

**Comment by mydea** [comment]
Are you using fastboot and/or embroider?

**Comment by progmatic-99** [comment]
fastboot is used but that is disabled on development and only used in production. Build error still appear with fastboot disabled.

**Comment by mydea** [comment]
I have no fastboot setup anywhere right now, so a bit hard for me to debug without a proper reproduction. I'll see if I can figure something out tomorrow!

**Comment by mydea** [comment]
I tried to look into it, it seems to be some weird issue with how broccoli-plugin works - I created an issue there:
https://github.com/broccolijs/broccoli-plugin/issues/69

Not really sure where the "fault" is here, but I think the code in ember-l10n _should_ work.
